<?php

return [
    'profiles' => [
        'ceramic' => [
            'display_name' => 'Ceramic',
            'label' => 'Keramik',
            'icon' => '📦',
            'has_package_unit' => false,
            'fields' => [
                'type' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'brand' => ['type' => 'string', 'nullable' => false, 'autocomplete' => true],
                'sub_brand' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'code' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'color' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'form' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'packaging' => ['type' => 'string', 'nullable' => true, 'autocomplete' => false],
                'pieces_per_package' => ['type' => 'integer', 'nullable' => false],
                'dimension_length' => ['type' => 'decimal:2', 'nullable' => false],
                'dimension_width' => ['type' => 'decimal:2', 'nullable' => false],
                'dimension_thickness' => ['type' => 'decimal:2', 'nullable' => true],
                'price_per_package' => ['type' => 'decimal:2', 'nullable' => false],
                'store' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'address' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'photo' => ['type' => 'file', 'nullable' => true],
            ],
        ],
        'brick' => [
            'display_name' => 'Brick',
            'label' => 'Bata',
            'icon' => '🧱',
            'has_package_unit' => false,
            'fields' => [
                'type' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'brand' => ['type' => 'string', 'nullable' => false, 'autocomplete' => true],
                'form' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'dimension_length' => ['type' => 'decimal:2', 'nullable' => false],
                'dimension_width' => ['type' => 'decimal:2', 'nullable' => false],
                'dimension_height' => ['type' => 'decimal:2', 'nullable' => false],
                'price_per_piece' => ['type' => 'decimal:2', 'nullable' => false],
                'store' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'address' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'photo' => ['type' => 'file', 'nullable' => true],
            ],
        ],
        'cat' => [
            'display_name' => 'Cat',
            'label' => 'Cat',
            'icon' => '🎨',
            'has_package_unit' => true,
            'fields' => [
                'type' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'brand' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'sub_brand' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'color_code' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'color_name' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'form' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'package_unit' => ['type' => 'string', 'nullable' => true, 'autocomplete' => false],
                'package_weight_gross' => ['type' => 'decimal:2', 'nullable' => true],
                'package_weight_net' => ['type' => 'decimal:2', 'nullable' => true],
                'volume' => ['type' => 'decimal:2', 'nullable' => true],
                'volume_unit' => ['type' => 'string', 'nullable' => true, 'autocomplete' => false],
                'store' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'address' => ['type' => 'text', 'nullable' => true, 'autocomplete' => false],
                'purchase_price' => ['type' => 'decimal:2', 'nullable' => true],
                'price_unit' => ['type' => 'string', 'nullable' => true, 'autocomplete' => false],
                'comparison_price_per_kg' => ['type' => 'decimal:2', 'nullable' => true],
                'photo' => ['type' => 'file', 'nullable' => true],
            ],
        ],
        'cement' => [
            'display_name' => 'Cement',
            'label' => 'Semen',
            'icon' => '🪨',
            'has_package_unit' => true,
            'fields' => [
                'type' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'brand' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'sub_brand' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'code' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'color' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'package_unit' => ['type' => 'string', 'nullable' => true, 'autocomplete' => false],
                'package_weight_gross' => ['type' => 'decimal:2', 'nullable' => true],
                'package_weight_net' => ['type' => 'decimal:2', 'nullable' => true],
                'dimension_length' => ['type' => 'decimal:2', 'nullable' => true],
                'dimension_width' => ['type' => 'decimal:2', 'nullable' => true],
                'dimension_height' => ['type' => 'decimal:2', 'nullable' => true],
                'package_volume' => ['type' => 'decimal:2', 'nullable' => true],
                'store' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'address' => ['type' => 'text', 'nullable' => true, 'autocomplete' => false],
                'package_price' => ['type' => 'decimal:2', 'nullable' => true],
                'price_unit' => ['type' => 'string', 'nullable' => true, 'autocomplete' => false],
                'comparison_price_per_kg' => ['type' => 'decimal:2', 'nullable' => true],
                'photo' => ['type' => 'file', 'nullable' => true],
            ],
        ],
        'sand' => [
            'display_name' => 'Sand',
            'label' => 'Pasir',
            'icon' => '🟫',
            'has_package_unit' => true,
            'fields' => [
                'type' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'brand' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'package_unit' => ['type' => 'string', 'nullable' => true, 'autocomplete' => false],
                'package_weight_gross' => ['type' => 'decimal:2', 'nullable' => true],
                'package_weight_net' => ['type' => 'decimal:2', 'nullable' => true],
                'dimension_length' => ['type' => 'decimal:2', 'nullable' => true],
                'dimension_width' => ['type' => 'decimal:2', 'nullable' => true],
                'dimension_height' => ['type' => 'decimal:2', 'nullable' => true],
                'package_volume' => ['type' => 'decimal:2', 'nullable' => true],
                'store' => ['type' => 'string', 'nullable' => true, 'autocomplete' => true],
                'address' => ['type' => 'text', 'nullable' => true, 'autocomplete' => false],
                'package_price' => ['type' => 'decimal:2', 'nullable' => true],
                'comparison_price_per_m3' => ['type' => 'decimal:2', 'nullable' => true],
                'photo' => ['type' => 'file', 'nullable' => true],
            ],
        ],
    ],
];
